#  https://cloud.google.com/endpoints/docs/grpc/grpc-service-config
type: google.api.http
config_version: 3

http:
  rules:
    - selector: apssouza.book.v1.BookstoreService.ListBooks
      post: '/apis/v1/Bookstore.ListBooks'
      body: "*"

    - selector: apssouza.shelf.v1.ShelfService.CreateShelf
      post: '/apis/v1/ShelfService.CreateShelf'
      body: "*"